### ISSUE TITLE
ng server error(Error: Cannot find module '@angular-devkit/core')

### ISSUE THREAD

**Issue by kapit4n** [kapit4n/football-two#4]
module.js:549
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\u6062296\Documents\proj\examples\football-two\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by kapit4n** [comment]
[Related](https://github.com/angular/angular-cli/issues/9307)
